CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS inspections (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_id uuid REFERENCES clients(id),
    status TEXT,
    inspection_date DATE,
    property_address_street TEXT,
    property_address_unit TEXT,
    property_address_city TEXT,
    property_address_state TEXT,
    property_address_zip TEXT,
    prelisting BOOLEAN,
    root_cut BOOLEAN,
    client_located_access BOOLEAN,
    length_of_lateral TEXT,
    payment_status TEXT,
    payment_status_amount NUMERIC,
    office_notes TEXT,
    check_num INTEGER,
    online BOOLEAN,
    cc_attached BOOLEAN,
    usb_num INTEGER,
    opening_observations TEXT,
    occupancy TEXT,
    outbuilding BOOLEAN,
    outbuilding_has_plumbing BOOLEAN,
    outbuilding_has_cleanout BOOLEAN,
    outbuilding_pipe_diameter TEXT,
    cccsd BOOLEAN,
    cccsd_unpermitted_work BOOLEAN,
    created TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified TIMESTAMPTZ NOT NULL DEFAULT now()
);
